flowchart TB
    classDef emphasis fill:#03A062;

    tracks[keypoint tracks] --> cleaning

    subgraph cleaning
    direction TB

    drop["drop bad values"]
    interp["interpolate"]
    smooth["smooth"]
    transform
    end

    subgraph fit["fit shape"]
    direction TB

    ellipse
    bbox["bounding box"]
    center["center-of-mass"]
    end

    subgraph kinematics
    direction TB

    size
    angle["joint angle"]
    orientation
    velocity["(angular) velocity"]
    acceleration["(angular) acceleration"]
    end


    fit -.-> kinematics
    cleaning ---> kinematics
    cleaning -.-> fit

    class tracks emphasis
    class velocity emphasis
    class acceleration emphasis
    class orientation emphasis
    class size emphasis
    class speed emphasis
    class angle emphasis
