flowchart TB

    classDef emphasis fill:#03A062;

    subgraph infrastructure
    direction TB
    website([website]) --> Main & HowTo & Skills[Software skills]
    data([data management]) --> SWC-BIDS & DataShuttle & DataSquash
    utils([utils]) --> python-cookiecutter & actions
    end


    subgraph Niko
    direction TB
    zoo["Zoo: WAZP"]
    movement
    pose["Pose estimation on HPC"]
    end
    class movement emphasis

    infrastructure --> |histology| BrainGlobe 
    infrastructure -->|ephys| swc_ephys
    infrastructure -->|behav| Niko
    infrastructure -->|funcimg| rsp-vision
