flowchart TB
    classDef emphasis fill:#03A062;

    video -->|preprocessing / compression| video2["processed video"]
    video2 -->|pose estimation + tracking| tracks["pose tracks"]
    tracks --> |calculations| kinematics
    tracks -->|classifiers| actions["actions / behav syllables"]
    video2 --> |comp vision| actions
